// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseRTSP() {
  return window['go']['main']['App']['CloseRTSP']();
}

export function MsgBox(arg1) {
  return window['go']['main']['App']['MsgBox'](arg1);
}

export function RTSP(arg1) {
  return window['go']['main']['App']['RTSP'](arg1);
}
