// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseStream():Promise<void>;

export function MsgBox(arg1:string):Promise<void>;

export function PlayStream(arg1:string):Promise<boolean>;
