// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseStream() {
  return window['go']['main']['App']['CloseStream']();
}

export function MsgBox(arg1) {
  return window['go']['main']['App']['MsgBox'](arg1);
}

export function PlayStream(arg1) {
  return window['go']['main']['App']['PlayStream'](arg1);
}
